project:
  title: "Decision making under uncertainty using matrices"
  output-dir: _output
  render:
    - ./docs/l-shaped-slides.qmd
format:
  html:
    toc: true
    html-math-method: katex
    code-fold: true
    number-sections: true
  pdf:
    toc: true
    documentclass: report
    margin-left: 30mm
    margin-right: 30mm
    number-sections: true
  revealjs:
    scrollable: true
    smaller: true
    html-math-method: katex
    self-contained-math: true
    chalkboard: true
    auto-stretch: true
    width: 125%
    height: 125%
